int treewalk (Ast *node)
{
  int semantico;
  switch(node->value)
  {

    case 84: semantico = treewalk(node->a); break; 
    case 85: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 86: semantico = treewalk(node->a); break;
    case 87: semantico = treewalk(node->a); break;
    case 88: semantico = treewalk(node->a);  break;
    case 89: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 90: semantico = treewalk(node->a); break;
    case 91: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); treewalk(node->d); break;
    case 92: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 93: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) ; break;
    case 94: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 95: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 96: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 97: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 98: semantico = treewalk(node->a); break;
    case 99: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 100: semantico = treewalk(node->a); break;
    case 101: semantico = treewalk(node->a); break;
    case 102: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 103: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 104: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 105: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) ; break;
    case 106: semantico = treewalk(node->a); break;
    case 107: semantico = treewalk(node->a); break;
    case 108: semantico = treewalk(node->a); break;
    case 109: semantico = treewalk(node->a); break;
    case 110: semantico = treewalk(node->a); break;
    case 111: semantico = treewalk(node->a); break;
    case 112: semantico = treewalk(node->a); break;
    case 113: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) ; break;
    case 114: semantico = treewalk(node->a); break;
    case 115: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 116: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 117: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 118: semantico = treewalk(node->a); break;
    case 119: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 120: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 121: semantico = treewalk(node->a); break;
    case 122: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 123: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 124: semantico = treewalk(node->a); break;
    case 125: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 126: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 127: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 128: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 129: semantico = treewalk(node->a); break;
    case 130: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 131: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 132: semantico = treewalk(node->a); break;
    case 133: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 134: semantico = treewalk(node->a); break;
    case 135: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 136: semantico = treewalk(node->a); break;
    case 137: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 138: semantico = treewalk(node->a); break;
    case 139: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 140: semantico = treewalk(node->a); break;
    case 141: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 142: semantico = treewalk(node->a); break;
    case 143: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) + treewalk(node->e) ; break;
    case 144: semantico = treewalk(node->a); break;
    case 145: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 146: semantico = treewalk(node->a); break;
    case 147: semantico = treewalk(node->a); break;
    case 148: semantico = treewalk(node->a); break;
    case 149: semantico = treewalk(node->a); break;
    case 150: semantico = treewalk(node->a); break;
    case 151: semantico = treewalk(node->a); break;
    case 152: semantico = treewalk(node->a); break;
    case 153: semantico = treewalk(node->a); break;
    case 154: semantico = treewalk(node->a); break;
    case 155: semantico = treewalk(node->a); break;
    case 156: semantico = treewalk(node->a); break;
    case 157: semantico = treewalk(node->a); break;
    case 158: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 159: semantico = treewalk(node->a); break;
    case 160: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 161: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 162: semantico = treewalk(node->a); break;
    case 163: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 164: semantico = treewalk(node->a); break;
    case 165: semantico = treewalk(node->a); break;
    case 166: semantico = treewalk(node->a); break;
    case 167: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 168: semantico = treewalk(node->a); break;
    case 169: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 170: semantico = treewalk(node->a); break;
    case 171: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 172: semantico = treewalk(node->a); break;
    case 173: semantico = treewalk(node->a); break;
    case 174: semantico = treewalk(node->a); break;
    case 175: semantico = treewalk(node->a); break;
    case 176: semantico = treewalk(node->a); break;
    case 177: semantico = treewalk(node->a); break;
    case 178: semantico = treewalk(node->a); break;
    case 179: semantico = treewalk(node->a); break;
    case 180: semantico = treewalk

(node->a); break;
    case 181: semantico = treewalk(node->a); break;
    case 182: semantico = treewalk(node->a); break;
    case 183: semantico = treewalk(node->a); break;
    case 184: semantico = treewalk(node->a); break;
    case 185: semantico = treewalk(node->a); break;
    case 186: semantico = treewalk(node->a); break;
    case 187: semantico = treewalk(node->a); break;
    case 188: semantico = treewalk(node->a); break;
    case 189: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) + treewalk(node->e) ; break;
    case 190: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d); break;
    case 191: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 192: semantico = treewalk(node->a); break;
    case 193: semantico = treewalk(node->a); break;
    case 194: semantico = treewalk(node->a); break;
    case 195: semantico = treewalk(node->a) + treewalk(node->b);; break;
    case 196: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 197: semantico = treewalk(node->a) + treewalk(node->b);; break;
    case 198: semantico = treewalk(node->a); break;
    case 199: semantico = treewalk(node->a) + treewalk(node->b);; break;
    case 200: semantico = treewalk(node->a); break;
    case 201: semantico = treewalk(node->a); break;//
    case 202: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 203: semantico = treewalk(node->a); break;
    case 204: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 205: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 206: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) ; break;
    case 207: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) + treewalk(node->e) ; break;
    case 208: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 209: semantico = treewalk(node->a); break;
    case 210: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 211: semantico = treewalk(node->a); break;
    case 212: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 213: semantico = treewalk(node->a); break;
    case 214: semantico = treewalk(node->a); break;
    case 215: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 216: semantico = treewalk(node->a); break;
    case 217: semantico = treewalk(node->a); break;
    case 218: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 219: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) ; break;
    case 220: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 221: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) ; break;
    case 222: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) ; break;
    case 223: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 224: semantico = treewalk(node->a); break;
    case 225: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 226: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 227: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 228: semantico = treewalk(node->a); break;
    case 229: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 230: semantico = treewalk(node->a); break;
    case 231: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 232: semantico = treewalk(node->a); break;
    case 233: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 234: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 235: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 236: semantico = treewalk(node->a); break;
    case 237: semantico = treewalk(node->a); break;
    case 238: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 239: semantico = treewalk(node->a); break;
    case 240: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 241: semantico = treewalk(node->a); break;
    case 242: semantico = treewalk(node->a); break;
    case 243: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 244: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 245: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 246: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 247: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 248: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) ; break;
    case 249: semantico = treewalk(node->a) + treewalk(node->b); break;
    case 250: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 251: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 252: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) ; break;
    case 253: semantico = treewalk(node->a); break;//
    case 254: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 255: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) ; break;
    case 256: semantico = treewalk(node->a); break; //
    case 257: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 258: semantico = treewalk(node->a); break;
    case 259: semantico = treewalk(node->a); break;
    case 260: semantico = treewalk(node->a); break;
    case 261: semantico = treewalk(node->a); break;
    case 262: semantico = treewalk(node->a); break;
    case 263: semantico = treewalk(node->a); break;
    case 264: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;
    case 265: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d); break;//
    case 266: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;//
    case 267: semantico = treewalk(node->a) + treewalk(node->b) ; break;//
    case 268: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;//
    case 269: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;//
    case 270: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d); break;//
    case 271: semantico = treewalk(node->a); break;//
    case 272: semantico = treewalk(node->a) + treewalk(node->b); break;//
    case 273: semantico = treewalk(node->a); break;//
    case 274: semantico = treewalk(node->a) + treewalk(node->b); break;//
    case 275: semantico = treewalk(node->a); break;//
    case 276: semantico = treewalk(node->a) + treewalk(node->b); break;//
    case 277: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) + treewalk(node->e); break;//
    case 278: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) + treewalk(node->e) + treewalk(node->f) + treewalk(node->g); break;//
    case 279: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) + treewalk(node->e); break;//
    case 280: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) + treewalk(node->e); break;//
    case 281: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) + treewalk(node->e) + treewalk(node->f) + treewalk(node->g); break;//
    case 282: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) + treewalk(node->e) + treewalk(node->f); break;//
    case 283: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d) + treewalk(node->e) + treewalk(node->f) + treewalk(node->g);  break;//
    case 284: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;//
    case 285: semantico = treewalk(node->a) + treewalk(node->b); break;//
    case 286: semantico = treewalk(node->a) + treewalk(node->b); break;//
    case 287: semantico = treewalk(node->a) + treewalk(node->b); break;//
    case 288: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;//
    case 289: semantico = treewalk(node->a); break;//
    case 290: semantico = treewalk(node->a); break;//
    case 291: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c) + treewalk(node->d); break;//
    case 292: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;//
    case 293: semantico = treewalk(node->a) + treewalk(node->b) + treewalk(node->c); break;//
    case 294: semantico = treewalk(node->a) + treewalk(node->b); break;//
    
    
     default: semantico = 0; break;
  }

 if(node->text != 0)
 {
     printf(" %d %s\n",node->value,node->text);
 }
 else
 {
  printf(" %d \n",node->value);
 }

}